# Exercise 3: Numpy

Perform the follwing tasks:


In [27]:
#3.1: import the numpy library
import numpy as np

In [34]:
##3.2: create a random 10x10 array named A

A = np.random.rand(10,10)
A

array([[0.07081915, 0.74227859, 0.81921823, 0.21958727, 0.59478534,
        0.92701833, 0.65033592, 0.32208577, 0.8473236 , 0.05234842],
       [0.09399495, 0.36411004, 0.1985635 , 0.03439649, 0.42560178,
        0.68347912, 0.44894713, 0.36168629, 0.33922183, 0.45772353],
       [0.99020186, 0.19644402, 0.09855599, 0.19239616, 0.77895965,
        0.25421533, 0.71949458, 0.74980023, 0.92002425, 0.37690898],
       [0.82463229, 0.76358739, 0.14337831, 0.68005284, 0.44852259,
        0.86881922, 0.66615285, 0.9825974 , 0.93647529, 0.8537699 ],
       [0.97290997, 0.75501686, 0.07603892, 0.83332575, 0.34918902,
        0.73429712, 0.76464713, 0.43952209, 0.74423982, 0.44297429],
       [0.61627729, 0.02810618, 0.11209539, 0.12591966, 0.06903099,
        0.22926783, 0.54504553, 0.82976396, 0.46819544, 0.53220017],
       [0.60530271, 0.02473092, 0.50933681, 0.60093382, 0.79879044,
        0.8150238 , 0.50031422, 0.39596528, 0.55777164, 0.06486989],
       [0.24168418, 0.11702078, 0.6059596

In [29]:
#3.3: return only the odd rows of A
A[:,0::2]

array([[2.75519587e-01, 2.10156482e-01, 4.80739353e-01, 7.18883364e-01,
        8.05556973e-01],
       [4.19824946e-01, 8.55634610e-01, 1.45493184e-01, 7.44012417e-01,
        8.33735208e-01],
       [5.31673499e-01, 4.37297090e-01, 8.24164240e-01, 1.38414122e-02,
        7.31572462e-01],
       [1.92915164e-01, 3.10719737e-02, 2.47480530e-01, 7.21115775e-01,
        2.42012505e-01],
       [4.37755708e-01, 7.67529363e-01, 8.65001745e-01, 2.83683135e-01,
        7.86210368e-01],
       [8.89415358e-01, 4.46171697e-01, 6.81863667e-01, 7.99593202e-01,
        4.51150240e-01],
       [7.60586005e-01, 4.71487380e-01, 8.40684602e-01, 7.72667362e-01,
        6.11516208e-01],
       [7.09728225e-01, 5.83340281e-01, 6.56049293e-01, 7.74074476e-01,
        8.77042912e-01],
       [1.16159673e-04, 2.28950781e-01, 2.33875267e-01, 6.35403147e-01,
        2.56851275e-01],
       [2.90002004e-01, 4.24495095e-01, 3.59749568e-01, 4.02934810e-01,
        1.33528629e-01]])

In [30]:
#3.4: perform a matrix multiplication of A with it's transposed
res = np.multiply(A, A.transpose())
res

array([[7.59110428e-02, 2.49190790e-01, 1.11734632e-01, 1.88251250e-01,
        2.10446396e-01, 3.99725664e-01, 5.46772626e-01, 8.27139335e-02,
        9.35732342e-05, 2.79886775e-01],
       [2.49190790e-01, 5.34001196e-01, 7.60722758e-01, 3.47145873e-02,
        8.86499778e-03, 2.22563708e-02, 2.04226551e-01, 2.99615749e-01,
        7.82329087e-01, 9.40265761e-02],
       [1.11734632e-01, 7.60722758e-01, 1.91228744e-01, 2.76623242e-02,
        6.32570254e-01, 4.25772825e-02, 6.52605118e-03, 3.01795933e-02,
        1.67494087e-01, 1.71309282e-01],
       [1.88251250e-01, 3.47145873e-02, 2.76623242e-02, 4.63519720e-01,
        1.28299557e-01, 2.18048108e-01, 6.37062023e-01, 6.40799423e-03,
        1.87393777e-01, 3.69989326e-03],
       [2.10446396e-01, 8.86499778e-03, 6.32570254e-01, 1.28299557e-01,
        7.48228018e-01, 3.46305183e-01, 2.38488043e-01, 2.55549707e-01,
        1.83875160e-01, 1.11909637e-01],
       [3.99725664e-01, 2.22563708e-02, 4.25772825e-02, 2.18048108e-01,
   

In [31]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)
A
np.linalg.inv(A)
np.linalg.inv(A)
np.linalg.inv(A)
A

array([[2.75519587e-01, 5.93558799e-01, 2.10156482e-01, 9.75824017e-01,
        4.80739353e-01, 4.49425188e-01, 7.18883364e-01, 1.16543108e-01,
        8.05556973e-01, 9.65120140e-01],
       [4.19824946e-01, 7.30753854e-01, 8.55634610e-01, 7.35080604e-02,
        1.45493184e-01, 2.03790938e-01, 7.44012417e-01, 5.46027170e-01,
        8.33735208e-01, 9.88708369e-02],
       [5.31673499e-01, 8.89074319e-01, 4.37297090e-01, 8.90266079e-01,
        8.24164240e-01, 9.54280218e-02, 1.38414122e-02, 5.17358295e-02,
        7.31572462e-01, 4.03560099e-01],
       [1.92915164e-01, 4.72255520e-01, 3.10719737e-02, 6.80822826e-01,
        2.47480530e-01, 5.17604297e-01, 7.21115775e-01, 8.25006376e-02,
        2.42012505e-01, 1.84040643e-02],
       [4.37755708e-01, 6.09306740e-02, 7.67529363e-01, 5.18422833e-01,
        8.65001745e-01, 5.07880386e-01, 2.83683135e-01, 3.89528211e-01,
        7.86210368e-01, 3.11076501e-01],
       [8.89415358e-01, 1.09211778e-01, 4.46171697e-01, 4.21264100e-01,
   

In [32]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [35]:
b = np.where(A>0.5)
A[b] = A[b]/2
A

array([[0.07081915, 0.3711393 , 0.40960912, 0.21958727, 0.29739267,
        0.46350916, 0.32516796, 0.32208577, 0.4236618 , 0.05234842],
       [0.09399495, 0.36411004, 0.1985635 , 0.03439649, 0.42560178,
        0.34173956, 0.44894713, 0.36168629, 0.33922183, 0.45772353],
       [0.49510093, 0.19644402, 0.09855599, 0.19239616, 0.38947982,
        0.25421533, 0.35974729, 0.37490011, 0.46001212, 0.37690898],
       [0.41231614, 0.38179369, 0.14337831, 0.34002642, 0.44852259,
        0.43440961, 0.33307643, 0.4912987 , 0.46823765, 0.42688495],
       [0.48645499, 0.37750843, 0.07603892, 0.41666288, 0.34918902,
        0.36714856, 0.38232356, 0.43952209, 0.37211991, 0.44297429],
       [0.30813864, 0.02810618, 0.11209539, 0.12591966, 0.06903099,
        0.22926783, 0.27252276, 0.41488198, 0.46819544, 0.26610008],
       [0.30265136, 0.02473092, 0.2546684 , 0.30046691, 0.39939522,
        0.4075119 , 0.25015711, 0.39596528, 0.27888582, 0.06486989],
       [0.24168418, 0.11702078, 0.3029798